name: Detect unused code

on:
  workflow_dispatch

jobs:
  install-tools:
    runs-on: ubuntu-latest
    steps:
    - run: |
        npm install -g eslint
        npm install -g ts-unused-exports

  detect-unused-vars:
    runs-on: ubuntu-latest
    needs: install-tools
    strategy:
      fail-fast: false
      matrix:
        package:
        - fx-core
        - server
        - vscode-extension
        - manifest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Detect unused vars
      run: eslint --no-eslintrc --rule '{@typescript-eslint/no-unused-vars:error}' --env browser,es6,node --parser-options ecmaVersion:2018 --parser-options sourceType:"module" --parser '@typescript-eslint/parser' --plugin "@typescript-eslint" src/**/*.ts
      working-directory: packages/${{matrix.package}}

    - name: Detect unused exports
      run: ts-unused-exports .\tsconfig.json --excludePathsFromReport=src\index.ts
      working-directory: packages/${{matrix.package}}
